<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booking_history [
    <!ELEMENT booking_history (header, bookings)>
    <!ELEMENT header (title, member, exported_at, total_bookings)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT member (name, email, role)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT role (#PCDATA)>
    <!ELEMENT exported_at (#PCDATA)>
    <!ELEMENT total_bookings (#PCDATA)>
    <!ELEMENT bookings (booking*)>
    <!ELEMENT booking (id, booking_date, session, activity, location, trainer)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT booking_date (#PCDATA)>
    <!ELEMENT session (id, date, time, datetime)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT time (#PCDATA)>
    <!ELEMENT datetime (#PCDATA)>
    <!ELEMENT activity (name, description)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT location (name, address)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT trainer (name, email)>
]>
<booking_history>
    <header>
        <title>Booking History - Olivia Martinez</title>
        <member>
            <name>Olivia Martinez</name>
            <email>member1@hsg.com</email>
            <role>member</role>
        </member>
        <exported_at>12/3/2025 5:35:53 PM</exported_at>
        <total_bookings>9</total_bookings>
    </header>
    <bookings>
        <booking>
            <id>booking_98</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_96</id>
                <date>2025-11-15</date>
                <time>18:00:00</time>
                <datetime>2025-11-15T08:00:00.000Z</datetime>
            </session>
            <activity>
                <name>CrossFit</name>
                <description>Functional movements at high intensity.</description>
            </activity>
            <location>
                <name>Eastside Gym</name>
                <address>789 East St, Morningside, QLD</address>
            </location>
            <trainer>
                <name>Michael Brown</name>
                <email>trainer1@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_110</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_124</id>
                <date>2025-10-15</date>
                <time>07:00:00</time>
                <datetime>2025-10-14T21:00:00.000Z</datetime>
            </session>
            <activity>
                <name>Boxing</name>
                <description>Punching, Ducking and Bleeding !!!</description>
            </activity>
            <location>
                <name>Toowong Gym</name>
                <address>123 Queen street, Toowong, Brisbane</address>
            </location>
            <trainer>
                <name>Robert Anderson</name>
                <email>trainer5@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_144</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_133</id>
                <date>2025-11-03</date>
                <time>10:46:00</time>
                <datetime>2025-11-03T00:46:00.000Z</datetime>
            </session>
            <activity>
                <name>Activity-1007</name>
                <description>Description-1007-update</description>
            </activity>
            <location>
                <name>Downtown Gym</name>
                <address>123 Main St, Brisbane, QLD</address>
            </location>
            <trainer>
                <name>Mike Tyson</name>
                <email>mike@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_146</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_145</id>
                <date>2025-11-14</date>
                <time>18:00:00</time>
                <datetime>2025-11-14T08:00:00.000Z</datetime>
            </session>
            <activity>
                <name>Activity-1007</name>
                <description>Description-1007-update</description>
            </activity>
            <location>
                <name>Flex Gym</name>
                <address>555 Flex Ave, Woolloongabba, QLD</address>
            </location>
            <trainer>
                <name>Emma Taylor</name>
                <email>trainer4@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_153</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_60</id>
                <date>2025-11-20</date>
                <time>09:30:00</time>
                <datetime>2025-11-19T23:30:00.000Z</datetime>
            </session>
            <activity>
                <name>Calisthenics</name>
                <description>Strength training with body weight.</description>
            </activity>
            <location>
                <name>Victory Gym</name>
                <address>777 Victory Dr, Toowong, QLD</address>
            </location>
            <trainer>
                <name>Robert Anderson</name>
                <email>trainer5@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_154</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_149</id>
                <date>2025-12-01</date>
                <time>09:00:00</time>
                <datetime>2025-11-30T23:00:00.000Z</datetime>
            </session>
            <activity>
                <name>Boxing</name>
                <description>Punching, Ducking and Bleeding !!!</description>
            </activity>
            <location>
                <name>Power Gym</name>
                <address>444 Power Ln, Southbank, QLD</address>
            </location>
            <trainer>
                <name>Emma Taylor</name>
                <email>trainer4@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_155</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_151</id>
                <date>2025-12-01</date>
                <time>09:00:00</time>
                <datetime>2025-11-30T23:00:00.000Z</datetime>
            </session>
            <activity>
                <name>Boxing</name>
                <description>Punching, Ducking and Bleeding !!!</description>
            </activity>
            <location>
                <name>Flex Gym</name>
                <address>555 Flex Ave, Woolloongabba, QLD</address>
            </location>
            <trainer>
                <name>Michael Brown</name>
                <email>trainer1@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_156</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_150</id>
                <date>2025-12-01</date>
                <time>08:30:00</time>
                <datetime>2025-11-30T22:30:00.000Z</datetime>
            </session>
            <activity>
                <name>Boxing</name>
                <description>Punching, Ducking and Bleeding !!!</description>
            </activity>
            <location>
                <name>Eastside Gym</name>
                <address>789 East St, Morningside, QLD</address>
            </location>
            <trainer>
                <name>Michael Brown</name>
                <email>trainer1@hsg.com</email>
            </trainer>
        </booking>
        <booking>
            <id>booking_157</id>
            <booking_date>N/A</booking_date>
            <session>
                <id>session_148</id>
                <date>2025-12-01</date>
                <time>10:00:00</time>
                <datetime>2025-12-01T00:00:00.000Z</datetime>
            </session>
            <activity>
                <name>Pilates</name>
                <description>A relaxing yet powerful workout</description>
            </activity>
            <location>
                <name>Downtown Gym</name>
                <address>123 Main St, Brisbane, QLD</address>
            </location>
            <trainer>
                <name>Michael Brown</name>
                <email>trainer1@hsg.com</email>
            </trainer>
        </booking>
    </bookings>
</booking_history>