<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE weekly_sessions [
    <!ELEMENT weekly_sessions (header, week*)>
    <!ATTLIST weekly_sessions export-date CDATA #IMPLIED>
    <!ELEMENT header (title, period, trainer, exported_at, total_sessions)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT period (start, end)>
    <!ELEMENT start (#PCDATA)>
    <!ELEMENT end (#PCDATA)>
    <!ELEMENT trainer (name, email)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT exported_at (#PCDATA)>
    <!ELEMENT total_sessions (#PCDATA)>
    <!ELEMENT week (session*)>
    <!ATTLIST week start CDATA #IMPLIED>
    <!ATTLIST week end CDATA #IMPLIED>
    <!ATTLIST week label CDATA #IMPLIED>
    <!ELEMENT session (id, title, location, start, end, activity, location_details)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT activity (name)>
    <!ELEMENT location_details (name)>
]>
<weekly_sessions>
    <header>
        <title>Sessions - Michael Brown</title>
        <period>
            <start>2025-01-20</start>
            <end>2025-01-26</end>
        </period>
        <trainer>
            <name>Michael Brown</name>
            <email>michael.brown@hsg.com</email>
        </trainer>
        <exported_at>2025-01-19 09:15:00</exported_at>
        <total_sessions>2</total_sessions>
    </header>
    <week start="2025-01-20" end="2025-01-26" label="20/01/2025 - 26/01/2025">
        <session>
            <id>session_148</id>
            <title>Pilates</title>
            <location>Studio A</location>
            <start>2025-01-22T07:00:00</start>
            <end>2025-01-22T08:00:00</end>
            <activity>
                <name>Pilates</name>
            </activity>
            <location_details>
                <name>Studio A</name>
            </location_details>
        </session>
    </week>
    <week start="2025-01-27" end="2025-02-02" label="27/01/2025 - 02/02/2025">
        <session>
            <id>session_149</id>
            <title>Core Strength</title>
            <location>Studio B</location>
            <start>2025-01-29T18:00:00</start>
            <end>2025-01-29T19:00:00</end>
            <activity>
                <name>Core Strength</name>
            </activity>
            <location_details>
                <name>Studio B</name>
            </location_details>
        </session>
    </week>
</weekly_sessions>

