<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE weekly_sessions [
    <!ELEMENT weekly_sessions (header, week*)>
    <!ATTLIST weekly_sessions export-date CDATA #IMPLIED>
    <!ELEMENT header (title, period, trainer, exported_at, total_sessions)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT period (start, end)>
    <!ELEMENT start (#PCDATA)>
    <!ELEMENT end (#PCDATA)>
    <!ELEMENT trainer (name, email)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT exported_at (#PCDATA)>
    <!ELEMENT total_sessions (#PCDATA)>
    <!ELEMENT week (session*)>
    <!ATTLIST week start CDATA #IMPLIED>
    <!ATTLIST week end CDATA #IMPLIED>
    <!ATTLIST week label CDATA #IMPLIED>
    <!ELEMENT session (id, title, location, start, end, activity, location_details)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT activity (name)>
    <!ELEMENT location_details (name)>
]>
<weekly_sessions>
    <header>
        <title>Sessions - Sarah Johnson</title>
        <period>
            <start>All future sessions</start>
            <end>No date range specified</end>
        </period>
        <trainer>
            <name>Sarah Johnson</name>
            <email>trainer2@hsg.com</email>
        </trainer>
        <exported_at>2025-12-03 17:28:44</exported_at>
        <total_sessions>4</total_sessions>
    </header>
    <week start="2025-11-10" end="2025-11-16" label="10/11/2025 - 16/11/2025">

        <session>
            <id>session_52</id>
            <title>HIIT</title>
            <location>Westside Gym</location>
            <start>2025-11-13T13:30:00</start>
            <end>2025-11-13T14:30:00</end>
            <activity>
                <name>HIIT</name>
            </activity>
            <location_details>
                <name>Westside Gym</name>
            </location_details>
        </session>
    </week>
    <week start="2025-12-15" end="2025-12-21" label="15/12/2025 - 21/12/2025">

        <session>
            <id>session_57</id>
            <title>Spinning</title>
            <location>Power Gym</location>
            <start>2025-12-17T12:00:00</start>
            <end>2025-12-17T13:00:00</end>
            <activity>
                <name>Spinning</name>
            </activity>
            <location_details>
                <name>Power Gym</name>
            </location_details>
        </session>
    </week>
    <week start="2025-12-22" end="2025-12-28" label="22/12/2025 - 28/12/2025">

        <session>
            <id>session_62</id>
            <title>HIIT</title>
            <location>Westside Gym</location>
            <start>2025-12-22T11:30:00</start>
            <end>2025-12-22T12:30:00</end>
            <activity>
                <name>HIIT</name>
            </activity>
            <location_details>
                <name>Westside Gym</name>
            </location_details>
        </session>
        <session>
            <id>session_67</id>
            <title>Spinning</title>
            <location>Power Gym</location>
            <start>2025-12-27T10:00:00</start>
            <end>2025-12-27T11:00:00</end>
            <activity>
                <name>Spinning</name>
            </activity>
            <location_details>
                <name>Power Gym</name>
            </location_details>
        </session>
    </week>
</weekly_sessions>